version: "3"
services:

 Aplic:
  image: webapivylex
  container_name: Aplicacao
  #volumes:
  #- meu-segundo-volume
  networks:
   - teste-pessoal
 
  #ports:
  # - 3000:3000

# Aplicca:
#  image: dockerbanco
#  container_name: Certo
#  network_mode: none

#networks: 
#  teste-pessoal:
#   driver: bridge

#volumes:
# dockerbanco_quarto: